debug_adapter_capabilities <- function() {
  # nolint start
  list(
    "supportsConfigurationDoneRequest" = FALSE,
    "supportsFunctionBreakpoints" = FALSE,
    "supportsConditionalBreakpoints" = FALSE,
    "supportsHitConditionalBreakpoints" = FALSE,
    "supportsEvaluateForHovers" = FALSE,
    "exceptionBreakpointFilters" = list(),
    "supportsStepBack" = FALSE,
    "supportsSetVariable" = FALSE,
    "supportsRestartFrame" = FALSE,
    "supportsGotoTargetsRequest" = FALSE,
    "supportsStepInTargetsRequest" = FALSE,
    "supportsCompletionsRequest" = FALSE,
    "completionTriggerCharacters" = list(),
    "supportsModulesRequest" = FALSE,
    "additionalModuleColumns" = list(),
    "supportedChecksumAlgorithms" = list(),
    "supportsRestartRequest" = FALSE,
    "supportsExceptionOptions" = FALSE,
    "supportsValueFormattingOptions" = FALSE,
    "supportsExceptionInfoRequest" = FALSE,
    "supportTerminateDebuggee" = FALSE,
    "supportSuspendDebuggee" = FALSE,
    "supportsDelayedStackTraceLoading" = FALSE,
    "supportsLoadedSourcesRequest" = FALSE,
    "supportsLogPoints" = FALSE,
    "supportsTerminateThreadsRequest" = FALSE,
    "supportsSetExpression" = FALSE,
    "supportsTerminateRequest" = FALSE,
    "supportsDataBreakpoints" = FALSE,
    "supportsReadMemoryRequest" = FALSE,
    "supportsWriteMemoryRequest" = FALSE,
    "supportsDisassembleRequest" = FALSE,
    "supportsCancelRequest" = FALSE,
    "supportsBreakpointLocationsRequest" = FALSE,
    "supportsClipboardContext" = FALSE,
    "supportsSteppingGranularity" = FALSE,
    "supportsInstructionBreakpoints" = FALSE,
    "supportsExceptionFilterOptions" = FALSE,
    "supportsSingleThreadExecutionRequests" = FALSE
  )
  # nolint end
}
